const T = {
  passport: {
    es: 'Fotocopia de todas las páginas del pasaporte, incluidas las páginas en blanco. Debe estar en vigor.',
    ca: 'Fotocòpia de totes les pàgines del passaport, incloses les pàgines en blanc. Ha d\'estar en vigor.',
    en: 'Photocopy of all passport pages, including blank pages. Must be valid.',
    ar: 'صورة من جميع صفحات جواز السفر، بما في ذلك الصفحات الفارغة. يجب أن يكون سارياً.',
    zh: '护照所有页面的复印件，包括空白页。必须在有效期内。',
    ru: 'Ксерокопия всех страниц паспорта, включая пустые. Должен быть действующим.',
    uk: 'Ксерокопія всіх сторінок паспорта, включно з порожніми. Має бути чинним.',
  },
  empadronamiento: {
    es: 'Documento que acredita tu residencia en el municipio. Se obtiene en el Ayuntamiento. Debe ser reciente (máx. 3 meses).',
    ca: 'Document que acredita la teva residència al municipi. S\'obté a l\'Ajuntament. Ha de ser recent (màx. 3 mesos).',
    en: 'Document proving your registration in the municipality. Obtained from the town hall. Must be recent (max. 3 months).',
    ar: 'وثيقة تثبت إقامتك في البلدية. تُحصل عليها من البلدية. يجب أن تكون حديثة (بحد أقصى 3 أشهر).',
    zh: '证明您在该市镇登记居住的文件，在市政厅获取，需为近期文件（最多3个月）。',
    ru: 'Документ, подтверждающий вашу регистрацию в муниципалитете. Выдаётся в мэрии. Должен быть недавним (макс. 3 месяца).',
    uk: 'Документ, що підтверджує вашу реєстрацію в муніципалітеті. Видається в мерії. Має бути недавнім (макс. 3 місяці).',
  },
  ex01: {
    es: 'Solicitud de autorización de residencia temporal. Disponible en el sitio web del Ministerio del Interior.',
    ca: 'Sol·licitud d\'autorització de residència temporal. Disponible al web del Ministeri de l\'Interior.',
    en: 'Application form for temporary residence authorisation. Available on the Ministry of Interior website.',
    ar: 'نموذج طلب تصريح الإقامة المؤقتة. متاح على موقع وزارة الداخلية.',
    zh: '临时居留授权申请表。可在内政部网站下载。',
    ru: 'Форма заявки на временный вид на жительство. Доступна на сайте Министерства внутренних дел.',
    uk: 'Форма заявки на тимчасовий дозвіл на проживання. Доступна на сайті Міністерства внутрішніх справ.',
  },
  mediosEconomicos: {
    es: 'Acredita ingresos suficientes para vivir en España. Válidas las últimas 3 nóminas o extracto bancario de los últimos 3 meses.',
    ca: 'Acredita ingressos suficients per viure a Espanya. Vàlides les últimes 3 nòmines o extracte bancari dels últims 3 mesos.',
    en: 'Proves you have sufficient income to live in Spain. Last 3 pay slips or a 3-month bank statement are accepted.',
    ar: 'يثبت أن لديك دخلاً كافياً للعيش في إسبانيا. مقبول آخر 3 كشوف رواتب أو كشف حساب بنكي لآخر 3 أشهر.',
    zh: '证明您有足够的收入在西班牙生活。接受最近3个月工资单或银行流水。',
    ru: 'Подтверждает достаточный доход для проживания в Испании. Принимаются последние 3 расчётных листка или выписка из банка за 3 месяца.',
    uk: 'Підтверджує достатній дохід для проживання в Іспанії. Приймаються останні 3 розрахункові листки або банківська виписка за 3 місяці.',
  },
  seguroMedico: {
    es: 'Seguro médico privado que cubra España, sin carencia y con cobertura completa sin copagos.',
    ca: 'Assegurança mèdica privada que cobreixi Espanya, sense carència i amb cobertura completa sense copagaments.',
    en: 'Private health insurance covering Spain. No waiting period, full coverage without co-payments.',
    ar: 'تأمين صحي خاص يغطي إسبانيا، بدون فترة انتظار وبتغطية كاملة بدون مشاركة في الرسوم.',
    zh: '覆盖西班牙的私人医疗保险，无等待期，完整保障（无共付额）。',
    ru: 'Частная медицинская страховка с покрытием в Испании. Без периода ожидания, полное покрытие без доплат.',
    uk: 'Приватна медична страховка з покриттям в Іспанії. Без терміну очікування, повне покриття без доплат.',
  },
  tasa790_052: {
    es: 'Comprobante de pago de la tasa modelo 790-052. Se abona en banco o por medios electrónicos.',
    ca: 'Comprovant de pagament de la taxa model 790-052. S\'abona al banc o per mitjans electrònics.',
    en: 'Proof of form 790-052 administrative fee payment. Paid at a bank or electronically.',
    ar: 'إيصال دفع رسوم النموذج 790-052. يُدفع في البنك أو إلكترونياً.',
    zh: '790-052表格行政费用缴纳凭证，通过银行或电子方式缴纳。',
    ru: 'Квитанция об оплате административного сбора по форме 790-052. Оплачивается в банке или электронным способом.',
    uk: 'Квитанція про сплату адміністративного збору за формою 790-052. Сплачується в банку або електронним способом.',
  },
  tasa790_012: {
    es: 'Comprobante de pago de la tasa modelo 790-012. Se abona en banco o por medios electrónicos.',
    ca: 'Comprovant de pagament de la taxa model 790-012. S\'abona al banc o per mitjans electrònics.',
    en: 'Proof of form 790-012 administrative fee payment. Paid at a bank or electronically.',
    ar: 'إيصال دفع رسوم النموذج 790-012. يُدفع في البنك أو إلكترونياً.',
    zh: '790-012表格行政费用缴纳凭证，通过银行或电子方式缴纳。',
    ru: 'Квитанция об оплате административного сбора по форме 790-012. Оплачивается в банке или электронным способом.',
    uk: 'Квитанція про сплату адміністративного збору за формою 790-012. Сплачується в банку або електронним способом.',
  },
  tieActual: {
    es: 'Tu tarjeta de identificación de extranjero vigente, que acredita tu residencia actual en España.',
    ca: 'La teva targeta d\'identificació d\'estranger vigent, que acredita la teva residència actual a Espanya.',
    en: 'Your current foreigner identification card, proving your current residence in Spain.',
    ar: 'بطاقة هويتك الحالية للأجانب، التي تثبت إقامتك الحالية في إسبانيا.',
    zh: '您当前有效的外国人身份证，证明您在西班牙的当前居留状态。',
    ru: 'Ваша действующая карточка иностранного резидента, подтверждающая текущее место жительства в Испании.',
    uk: 'Ваша чинна картка іноземного резидента, що підтверджує поточне місце проживання в Іспанії.',
  },
  ex17: {
    es: 'Formulario de renovación de la autorización de residencia temporal. Disponible en el Ministerio del Interior.',
    ca: 'Formulari de renovació de l\'autorització de residència temporal. Disponible al Ministeri de l\'Interior.',
    en: 'Renewal form for temporary residence authorisation. Available from the Ministry of Interior.',
    ar: 'نموذج تجديد تصريح الإقامة المؤقتة. متاح من وزارة الداخلية.',
    zh: '临时居留授权续签表格，可从内政部获取。',
    ru: 'Форма продления разрешения на временное проживание. Доступна в Министерстве внутренних дел.',
    uk: 'Форма продовження дозволу на тимчасове проживання. Доступна в Міністерстві внутрішніх справ.',
  },
  fotografia: {
    es: 'Fotografía tipo carnet, fondo blanco, tomada en los últimos 6 meses. Tamaño 32×26 mm.',
    ca: 'Fotografia tipus carnet, fons blanc, presa en els últims 6 mesos. Mida 32×26 mm.',
    en: 'Passport-type photo with white background, taken within the last 6 months. Size 32×26 mm.',
    ar: 'صورة بطاقة تعريف بخلفية بيضاء، مأخوذة خلال الأشهر الست الماضية. حجم 32×26 ملم.',
    zh: '近6个月内拍摄的白底证件照，尺寸32×26毫米。',
    ru: 'Фото на документ с белым фоном, сделанное в течение последних 6 месяцев. Размер 32×26 мм.',
    uk: 'Фото на документ з білим тлом, зроблене протягом останніх 6 місяців. Розмір 32×26 мм.',
  },
  situacionLaboral: {
    es: 'Acredita tu situación laboral actual: contrato de trabajo vigente o las últimas 3 nóminas.',
    ca: 'Acredita la teva situació laboral actual: contracte de treball vigent o les últimes 3 nòmines.',
    en: 'Proves your current employment status: valid employment contract or last 3 pay slips.',
    ar: 'يثبت وضعك الوظيفي الحالي: عقد عمل ساري أو آخر 3 كشوف رواتب.',
    zh: '证明当前工作状态：有效劳动合同或最近3个月工资单。',
    ru: 'Подтверждает текущее трудовое положение: действующий трудовой договор или последние 3 расчётных листка.',
    uk: 'Підтверджує поточний трудовий статус: чинний трудовий договір або останні 3 розрахункові листки.',
  },
  pasaporteReagrupante: {
    es: 'Pasaporte del familiar residente en España que solicita la reagrupación. Debe estar en vigor.',
    ca: 'Passaport del familiar resident a Espanya que sol·licita la reagrupació. Ha d\'estar en vigor.',
    en: 'Passport of the family member residing in Spain who is applying for reunification. Must be valid.',
    ar: 'جواز سفر الفرد المقيم في إسبانيا الذي يطلب لم الشمل. يجب أن يكون سارياً.',
    zh: '在西班牙居住的申请人的护照，须在有效期内。',
    ru: 'Паспорт члена семьи, проживающего в Испании и подающего заявку на воссоединение. Должен быть действующим.',
    uk: 'Паспорт члена сім\'ї, що проживає в Іспанії та подає заявку на возз\'єднання. Має бути чинним.',
  },
  tieReagrupante: {
    es: 'Tarjeta de residencia vigente del familiar que solicita la reagrupación, acreditando su residencia legal.',
    ca: 'Targeta de residència vigent del familiar que sol·licita la reagrupació, acreditant la seva residència legal.',
    en: 'Valid residence card of the family member applying for reunification, proving legal resident status.',
    ar: 'بطاقة إقامة سارية للفرد الذي يطلب لم الشمل، تثبت إقامته القانونية.',
    zh: '申请人的有效居留证，证明其为合法居民。',
    ru: 'Действующая карточка резидента члена семьи, подтверждающая статус законного резидента.',
    uk: 'Чинна картка резидента члена сім\'ї, що підтверджує статус законного резидента.',
  },
  ex02: {
    es: 'Formulario de solicitud de reagrupación familiar. Disponible en el Ministerio del Interior.',
    ca: 'Formulari de sol·licitud de reagrupació familiar. Disponible al Ministeri de l\'Interior.',
    en: 'Family reunification application form. Available from the Ministry of Interior.',
    ar: 'نموذج طلب لم شمل الأسرة. متاح من وزارة الداخلية.',
    zh: '家庭团聚申请表格，可从内政部获取。',
    ru: 'Форма заявки на воссоединение семьи. Доступна в Министерстве внутренних дел.',
    uk: 'Форма заявки на возз\'єднання сім\'ї. Доступна в Міністерстві внутрішніх справ.',
  },
  vinculoFamiliar: {
    es: 'Documentos que demuestran el parentesco (actas de matrimonio, nacimiento, etc.). Deben estar apostillados y traducidos si no están en español.',
    ca: 'Documents que demostren el parentiu (actes de matrimoni, naixement, etc.). Han d\'estar apostillats i traduïts si no estan en castellà.',
    en: 'Documents proving family ties (marriage certificates, birth certificates, etc.). Must be apostilled and translated if not in Spanish.',
    ar: 'وثائق تثبت صلة القرابة (عقود الزواج وشهادات الميلاد وغيرها). يجب تصديقها بالأبوستيل وترجمتها إن لم تكن بالإسبانية.',
    zh: '证明亲属关系的文件（结婚证、出生证明等）。须附使馆认证，如非西班牙语则需翻译。',
    ru: 'Документы, подтверждающие семейные связи (свидетельства о браке, рождении и т.д.). Должны быть апостилированы и переведены, если не на испанском.',
    uk: 'Документи, що підтверджують сімейні зв\'язки (свідоцтва про шлюб, народження тощо). Мають бути апостильовані та перекладені, якщо не іспанською.',
  },
  vivienda: {
    es: 'Acredita que dispones de vivienda con condiciones de habitabilidad para los familiares: informe municipal de habitabilidad o escritura/contrato de alquiler.',
    ca: 'Acredita que disposes d\'un habitatge amb condicions d\'habitabilitat per als familiars: informe municipal o escriptura/contracte de lloguer.',
    en: 'Proves you have housing with adequate living conditions for family members: municipal habitability report or property deed/rental contract.',
    ar: 'يثبت أن لديك مسكناً بظروف معيشية مناسبة للأسرة: تقرير بلدي أو عقد الملكية/الإيجار.',
    zh: '证明您有适合家庭成员居住的住所：市政宜居报告或房产证/租房合同。',
    ru: 'Подтверждает наличие жилья с надлежащими условиями для родственников: муниципальный акт о пригодности или договор собственности/аренды.',
    uk: 'Підтверджує наявність житла з належними умовами для родичів: муніципальний акт про придатність або договір власності/оренди.',
  },
  ofertaTrabajo: {
    es: 'Documento firmado por el empleador que garantiza la contratación: cargo, salario, jornada y duración.',
    ca: 'Document signat per l\'empresari que garanteix la contractació: lloc, salari, jornada i durada.',
    en: 'Document signed by the employer guaranteeing the job: position, salary, working hours and duration.',
    ar: 'وثيقة موقعة من صاحب العمل تضمن التوظيف: المنصب والراتب وساعات العمل والمدة.',
    zh: '由雇主签署的保证聘用的文件，须注明职位、薪资、工作时间和合同期限。',
    ru: 'Документ, подписанный работодателем, гарантирующий трудоустройство: должность, зарплата, рабочее время и срок.',
    uk: 'Документ, підписаний роботодавцем, що гарантує працевлаштування: посада, зарплата, робочий час і строк.',
  },
  ex03: {
    es: 'Formulario de solicitud de autorización de trabajo por cuenta ajena. Disponible en el Ministerio del Interior.',
    ca: 'Formulari de sol·licitud d\'autorització de treball per compte aliè. Disponible al Ministeri de l\'Interior.',
    en: 'Application form for employee work authorisation. Available from the Ministry of Interior.',
    ar: 'نموذج طلب تصريح العمل لدى الغير. متاح من وزارة الداخلية.',
    zh: '受雇工作授权申请表格，可从内政部获取。',
    ru: 'Форма заявки на разрешение на работу по найму. Доступна в Министерстве внутренних дел.',
    uk: 'Форма заявки на дозвіл на роботу за наймом. Доступна в Міністерстві внутрішніх справ.',
  },
  docEmpresa: {
    es: 'Acredita la existencia legal de la empresa: NIF/CIF y escrituras de constitución o registro mercantil.',
    ca: 'Acredita l\'existència legal de l\'empresa: NIF/CIF i escriptures de constitució o registre mercantil.',
    en: 'Proves the company\'s legal existence: tax identification number and articles of incorporation or commercial registry.',
    ar: 'يثبت الوجود القانوني للشركة: الرقم الضريبي وعقد التأسيس أو السجل التجاري.',
    zh: '证明公司的合法存在：税号及公司章程/商业登记文件。',
    ru: 'Подтверждает юридическое существование компании: ИНН и учредительные документы или торговый реестр.',
    uk: 'Підтверджує юридичне існування компанії: ідентифікаційний номер та установчі документи або торговий реєстр.',
  },
  titulacion: {
    es: 'Diploma, título universitario o certificado que acredite tu cualificación profesional para el puesto o actividad solicitada.',
    ca: 'Diploma, títol universitari o certificat que acrediti la teva qualificació professional per al lloc o activitat sol·licitada.',
    en: 'Diploma, university degree or certificate proving your professional qualification for the applied position or activity.',
    ar: 'دبلوم أو شهادة جامعية أو شهادة تثبت مؤهلك المهني للوظيفة أو النشاط المطلوب.',
    zh: '证明您具有申请职位或业务所需专业资质的文凭、大学学位或证书。',
    ru: 'Диплом, учёная степень или сертификат, подтверждающий профессиональную квалификацию для данной должности или деятельности.',
    uk: 'Диплом, університетський ступінь або сертифікат, що підтверджує професійну кваліфікацію для даної посади або діяльності.',
  },
  planNegocio: {
    es: 'Descripción de tu actividad, mercado objetivo, proyecciones financieras y viabilidad como autónomo o empresario.',
    ca: 'Descripció de la teva activitat, mercat objectiu, projeccions financeres i viabilitat com a autònom o empresari.',
    en: 'Description of your activity, target market, financial projections and viability as a freelancer or entrepreneur.',
    ar: 'وصف نشاطك والسوق المستهدف والتوقعات المالية والجدوى كعامل مستقل أو رائد أعمال.',
    zh: '描述您作为自由职业者或创业者的业务活动、目标市场、财务预测和可行性。',
    ru: 'Описание деятельности, целевого рынка, финансовых прогнозов и жизнеспособности как фрилансера или предпринимателя.',
    uk: 'Опис діяльності, цільового ринку, фінансових прогнозів та життєздатності як фрілансера або підприємця.',
  },
  ex07: {
    es: 'Formulario de solicitud de autorización de trabajo por cuenta propia. Disponible en el Ministerio del Interior.',
    ca: 'Formulari de sol·licitud d\'autorització de treball per compte propi. Disponible al Ministeri de l\'Interior.',
    en: 'Application form for self-employment work authorisation. Available from the Ministry of Interior.',
    ar: 'نموذج طلب تصريح العمل الحر. متاح من وزارة الداخلية.',
    zh: '自雇工作授权申请表格，可从内政部获取。',
    ru: 'Форма заявки на разрешение на самозанятость. Доступна в Министерстве внутренних дел.',
    uk: 'Форма заявки на дозвіл на самозайнятість. Доступна в Міністерстві внутрішніх справ.',
  },
  licencias: {
    es: 'Licencias específicas del sector de tu actividad (sanitarias, alimentarias, etc.) exigidas por la normativa española.',
    ca: 'Llicències específiques del sector de la teva activitat (sanitàries, alimentàries, etc.) exigides per la normativa espanyola.',
    en: 'Sector-specific licences for your activity (health, food, etc.) required by Spanish regulations.',
    ar: 'تراخيص قطاعية محددة لنشاطك (صحية وغذائية وغيرها) مطلوبة بموجب اللوائح الإسبانية.',
    zh: '您业务活动所需的特定行业许可证（卫生、食品等），符合西班牙法规要求。',
    ru: 'Отраслевые лицензии для вашей деятельности (санитарные, пищевые и т.д.), требуемые испанским законодательством.',
    uk: 'Галузеві ліцензії для вашої діяльності (санітарні, харчові тощо), що вимагаються іспанським законодавством.',
  },
  nieTie: {
    es: 'NIE o tarjeta de residencia válidos para demostrar tu presencia legal previa en España.',
    ca: 'NIE o targeta de residència vàlids per demostrar la teva presència legal prèvia a Espanya.',
    en: 'Valid NIE or residence card needed to prove your prior legal presence in Spain.',
    ar: 'NIE أو بطاقة إقامة سارية لإثبات وجودك القانوني السابق في إسبانيا.',
    zh: '有效的NIE或居留证，用于证明您之前在西班牙的合法存在。',
    ru: 'Действующий NIE или карточка резидента для подтверждения предыдущего законного пребывания в Испании.',
    uk: 'Чинний NIE або картка резидента для підтвердження попереднього законного перебування в Іспанії.',
  },
  empadronamientoHistorico: {
    es: 'Certifica todos los periodos de empadronamiento en España. Se obtiene en el Ayuntamiento. Imprescindible para la nacionalidad.',
    ca: 'Certifica tots els períodes d\'empadronament a Espanya. S\'obté a l\'Ajuntament. Imprescindible per a la nacionalitat.',
    en: 'Certifies all periods of registered residence in Spain. Obtained from the town hall. Essential for nationality applications.',
    ar: 'يشهد على جميع فترات الإقامة المسجلة في إسبانيا. تُحصل عليه من البلدية. ضروري لطلبات الجنسية.',
    zh: '证明在西班牙所有户籍登记期的证明，在市政厅获取，申请国籍必备。',
    ru: 'Подтверждает все периоды регистрации проживания в Испании. Выдаётся в мэрии. Обязателен для заявки на гражданство.',
    uk: 'Підтверджує всі періоди реєстрації проживання в Іспанії. Видається в мерії. Обов\'язковий для заявки на громадянство.',
  },
  antecedentespenales: {
    es: 'Certificado de no tener antecedentes penales en tu país de origen. Debe estar apostillado y traducido al español si procede.',
    ca: 'Certificat de no tenir antecedents penals al teu país d\'origen. Ha d\'estar apostillat i traduït al castellà si escau.',
    en: 'Certificate of no criminal record in your country of origin. Must be apostilled and translated into Spanish if needed.',
    ar: 'شهادة بعدم وجود سجل جنائي في بلدك الأصلي. يجب تصديقها بالأبوستيل وترجمتها إلى الإسبانية إذا لزم الأمر.',
    zh: '原籍国的无犯罪记录证明。须附使馆认证，如非西班牙语则需官方翻译。',
    ru: 'Справка об отсутствии судимостей в стране происхождения. Должна быть апостилирована и переведена на испанский при необходимости.',
    uk: 'Довідка про відсутність судимостей у країні походження. Має бути апостильована та перекладена іспанською при необхідності.',
  },
  nacimiento: {
    es: 'Acta de nacimiento original del país de origen, apostillada y con traducción jurada al español si procede.',
    ca: 'Acta de naixement original del país d\'origen, apostillada i amb traducció jurada al castellà si escau.',
    en: 'Original birth certificate from the country of origin, apostilled and with sworn translation into Spanish if required.',
    ar: 'شهادة ميلاد أصلية من بلد المنشأ، مصدقة بالأبوستيل ومع ترجمة معتمدة إلى الإسبانية إذا لزم الأمر.',
    zh: '原籍国的原始出生证明，附使馆认证，如需要则附宣誓翻译。',
    ru: 'Оригинал свидетельства о рождении из страны происхождения, апостилированный и с нотариальным переводом при необходимости.',
    uk: 'Оригінал свідоцтва про народження з країни походження, апостильований та з нотаріальним перекладом при необхідності.',
  },
  dele: {
    es: 'Certificado oficial de nivel de español A2 o superior expedido por el Instituto Cervantes.',
    ca: 'Certificat oficial de nivell d\'espanyol A2 o superior expedit per l\'Institut Cervantes.',
    en: 'Official Spanish language certificate at A2 level or higher, issued by the Instituto Cervantes.',
    ar: 'شهادة رسمية في اللغة الإسبانية بمستوى A2 أو أعلى، صادرة عن Instituto Cervantes.',
    zh: '由塞万提斯学院颁发的西班牙语A2级或更高级别的官方语言证书。',
    ru: 'Официальный сертификат знания испанского языка уровня A2 или выше, выданный Институтом Сервантеса.',
    uk: 'Офіційний сертифікат знання іспанської мови рівня A2 або вищого, виданий Інститутом Сервантеса.',
  },
  ccse: {
    es: 'Prueba de conocimientos constitucionales y socioculturales de España, emitida por el Instituto Cervantes. Obligatoria para la nacionalidad.',
    ca: 'Prova de coneixements constitucionals i socioculturals d\'Espanya, emesa per l\'Institut Cervantes. Obligatòria per a la nacionalitat.',
    en: 'Test of constitutional and socio-cultural knowledge of Spain issued by the Instituto Cervantes. Required for nationality applications.',
    ar: 'اختبار المعرفة الدستورية والاجتماعية والثقافية لإسبانيا، تصدره Instituto Cervantes. إلزامي لطلبات الجنسية.',
    zh: '西班牙宪法及社会文化知识测试，由塞万提斯学院颁发，申请国籍必须通过。',
    ru: 'Тест на знание конституционных и социокультурных аспектов Испании. Выдаётся Институтом Сервантеса. Обязателен для заявки на гражданство.',
    uk: 'Тест на знання конституційних та соціокультурних аспектів Іспанії. Видається Інститутом Сервантеса. Обов\'язковий для заявки на громадянство.',
  },
  solicitudNacionalidad: {
    es: 'Formulario oficial de solicitud de la nacionalidad española, gestionado a través del Ministerio de Justicia.',
    ca: 'Formulari oficial de sol·licitud de la nacionalitat espanyola, gestionat a través del Ministeri de Justícia.',
    en: 'Official Spanish nationality application form, managed through the Ministry of Justice.',
    ar: 'نموذج طلب الجنسية الإسبانية الرسمي، تتم إدارته من خلال وزارة العدل.',
    zh: '申请西班牙国籍的官方表格，通过司法部办理。',
    ru: 'Официальная форма заявки на испанское гражданство, оформляется через Министерство юстиции.',
    uk: 'Офіційна форма заявки на іспанське громадянство, оформляється через Міністерство юстиції.',
  },
  motivoNIE: {
    es: 'Carta o documento que explica el motivo de la solicitud del NIE: compra de vivienda, trabajo, cuenta bancaria, etc.',
    ca: 'Carta o document que explica el motiu de la sol·licitud del NIE: compra d\'habitatge, treball, compte bancari, etc.',
    en: 'Letter or document explaining the reason for needing the NIE: property purchase, employment, bank account, etc.',
    ar: 'رسالة أو وثيقة توضح سبب الحاجة إلى NIE: شراء عقار أو عمل أو حساب بنكي وغيره.',
    zh: '说明您需要NIE原因的信件或文件：购房、工作、开设银行账户等。',
    ru: 'Письмо или документ, объясняющий причину необходимости NIE: покупка жилья, работа, банковский счёт и т.д.',
    uk: 'Лист або документ, що пояснює причину необхідності NIE: купівля житла, робота, банківський рахунок тощо.',
  },
  ex15: {
    es: 'Formulario de solicitud del NIE. Disponible en el Ministerio del Interior y comisarías de Policía Nacional.',
    ca: 'Formulari de sol·licitud del NIE. Disponible al Ministeri de l\'Interior i comissaries de Policia Nacional.',
    en: 'NIE application form. Available from the Ministry of Interior and National Police stations.',
    ar: 'نموذج طلب NIE. متاح من وزارة الداخلية ومراكز الشرطة الوطنية.',
    zh: 'NIE申请表格，可从内政部或国家警察局获取。',
    ru: 'Форма заявки на NIE. Доступна в Министерстве внутренних дел и отделениях Национальной полиции.',
    uk: 'Форма заявки на NIE. Доступна в Міністерстві внутрішніх справ та відділеннях Національної поліції.',
  },
  dniComunitario: {
    es: 'Documento de identidad nacional o pasaporte en vigor de un país de la Unión Europea.',
    ca: 'Document d\'identitat nacional o passaport en vigor d\'un país de la Unió Europea.',
    en: 'Valid national identity document or passport from a European Union country.',
    ar: 'وثيقة هوية وطنية أو جواز سفر ساريان من دولة عضو في الاتحاد الأوروبي.',
    zh: '有效的欧盟成员国国家身份证或护照。',
    ru: 'Действующее удостоверение личности или паспорт страны Европейского союза.',
    uk: 'Чинне посвідчення особи або паспорт країни Європейського союзу.',
  },
  ex18: {
    es: 'Formulario de solicitud del certificado de registro de ciudadano de la UE. Disponible en el Ministerio del Interior.',
    ca: 'Formulari de sol·licitud del certificat de registre de ciutadà de la UE. Disponible al Ministeri de l\'Interior.',
    en: 'Application form for the EU citizen registration certificate. Available from the Ministry of Interior.',
    ar: 'نموذج طلب شهادة تسجيل مواطن الاتحاد الأوروبي. متاح من وزارة الداخلية.',
    zh: '欧盟公民登记证申请表格，可从内政部获取。',
    ru: 'Форма заявки на свидетельство о регистрации гражданина ЕС. Доступна в Министерстве внутренних дел.',
    uk: 'Форма заявки на свідоцтво про реєстрацію громадянина ЄС. Доступна в Міністерстві внутрішніх справ.',
  },
  actividad: {
    es: 'Prueba de que realizas una actividad en España: contrato de trabajo, matrícula universitaria o medios económicos suficientes.',
    ca: 'Prova que realitzes una activitat a Espanya: contracte de treball, matrícula universitària o mitjans econòmics suficients.',
    en: 'Proof of activity in Spain: work contract, university enrolment or evidence of sufficient financial means.',
    ar: 'دليل على مزاولتك نشاطاً في إسبانيا: عقد عمل أو تسجيل جامعي أو إثبات موارد مالية كافية.',
    zh: '证明您在西班牙从事活动的文件：劳动合同、大学入学证明或足够经济来源证明。',
    ru: 'Подтверждение деятельности в Испании: трудовой договор, студенческий билет или доказательство достаточных финансовых средств.',
    uk: 'Підтвердження діяльності в Іспанії: трудовий договір, студентський квиток або доказ достатніх фінансових засобів.',
  },
  seguroMedicoUE: {
    es: 'Seguro médico privado si no estás dado de alta en la Seguridad Social española. Mismos requisitos que para residencia temporal.',
    ca: 'Assegurança mèdica privada si no estàs donat d\'alta a la Seguretat Social espanyola. Mateixos requisits que per a residència temporal.',
    en: 'Private health insurance if not registered with the Spanish Social Security. Same requirements as for temporary residence.',
    ar: 'تأمين صحي خاص إذا لم تكن مسجلاً في الضمان الاجتماعي الإسباني. نفس متطلبات الإقامة المؤقتة.',
    zh: '如果未在西班牙社会保障系统注册，则需提供私人医疗保险。要求与临时居留相同。',
    ru: 'Частная медицинская страховка, если не зарегистрирован в испанской системе соцобеспечения. Те же требования, что и для временного ВНЖ.',
    uk: 'Приватна медична страховка, якщо не зареєстрований в іспанській системі соцзабезпечення. Ті ж вимоги, що і для тимчасового дозволу.',
  },
};

function doc(name, tooltipKey) {
  return { name, tooltip: T[tooltipKey] };
}

export const DOCUMENTOS_REQUERIDOS = {
  residencia: {
    orientacion: [
      doc('Pasaporte (todas las páginas)', 'passport'),
      doc('Certificado de empadronamiento', 'empadronamiento'),
    ],
    revision: [
      doc('Pasaporte (todas las páginas)', 'passport'),
      doc('Certificado de empadronamiento', 'empadronamiento'),
      doc('Formulario EX-01 cumplimentado', 'ex01'),
      doc('Justificación medios económicos (3 últimas nóminas o extracto bancario)', 'mediosEconomicos'),
    ],
    gestion: [
      doc('Pasaporte (todas las páginas)', 'passport'),
      doc('Certificado de empadronamiento', 'empadronamiento'),
      doc('Formulario EX-01 cumplimentado', 'ex01'),
      doc('Justificación medios económicos (3 últimas nóminas o extracto bancario)', 'mediosEconomicos'),
      doc('Póliza de seguro médico', 'seguroMedico'),
      doc('Justificante tasa modelo 790-052', 'tasa790_052'),
    ],
  },
  tie: {
    orientacion: [
      doc('TIE actual', 'tieActual'),
      doc('Pasaporte en vigor', 'passport'),
    ],
    revision: [
      doc('TIE actual', 'tieActual'),
      doc('Pasaporte en vigor', 'passport'),
      doc('Formulario EX-17 cumplimentado', 'ex17'),
      doc('Fotografía reciente (fondo blanco)', 'fotografia'),
    ],
    gestion: [
      doc('TIE actual', 'tieActual'),
      doc('Pasaporte en vigor', 'passport'),
      doc('Formulario EX-17 cumplimentado', 'ex17'),
      doc('Fotografía reciente (fondo blanco)', 'fotografia'),
      doc('Justificación situación laboral (contrato o nóminas)', 'situacionLaboral'),
      doc('Justificante tasa modelo 790-012', 'tasa790_012'),
    ],
  },
  reagrupacion: {
    orientacion: [
      doc('Pasaporte del reagrupante', 'pasaporteReagrupante'),
      doc('TIE en vigor del reagrupante', 'tieReagrupante'),
    ],
    revision: [
      doc('Pasaporte del reagrupante', 'pasaporteReagrupante'),
      doc('TIE en vigor del reagrupante', 'tieReagrupante'),
      doc('Formulario EX-02 cumplimentado', 'ex02'),
      doc('Documentos acreditativos del vínculo familiar', 'vinculoFamiliar'),
      doc('Certificado de empadronamiento', 'empadronamiento'),
    ],
    gestion: [
      doc('Pasaporte del reagrupante', 'pasaporteReagrupante'),
      doc('TIE en vigor del reagrupante', 'tieReagrupante'),
      doc('Formulario EX-02 cumplimentado', 'ex02'),
      doc('Documentos acreditativos del vínculo familiar', 'vinculoFamiliar'),
      doc('Certificado de empadronamiento', 'empadronamiento'),
      doc('Justificación de vivienda adecuada', 'vivienda'),
      doc('Justificación de medios económicos', 'mediosEconomicos'),
      doc('Justificante tasa modelo 790-052', 'tasa790_052'),
    ],
  },
  trabajo_ajena: {
    orientacion: [
      doc('Pasaporte del trabajador', 'passport'),
      doc('Oferta de trabajo o precontrato', 'ofertaTrabajo'),
    ],
    revision: [
      doc('Pasaporte del trabajador', 'passport'),
      doc('Oferta de trabajo o precontrato', 'ofertaTrabajo'),
      doc('Formulario EX-03 cumplimentado', 'ex03'),
      doc('Documentación de la empresa empleadora (CIF, escrituras)', 'docEmpresa'),
    ],
    gestion: [
      doc('Pasaporte del trabajador', 'passport'),
      doc('Oferta de trabajo o precontrato', 'ofertaTrabajo'),
      doc('Formulario EX-03 cumplimentado', 'ex03'),
      doc('Documentación de la empresa empleadora (CIF, escrituras)', 'docEmpresa'),
      doc('Titulación o certificado de experiencia profesional', 'titulacion'),
      doc('Justificante tasa modelo 790-052', 'tasa790_052'),
    ],
  },
  trabajo_propia: {
    orientacion: [
      doc('Pasaporte en vigor', 'passport'),
      doc('Plan de negocio (borrador)', 'planNegocio'),
    ],
    revision: [
      doc('Pasaporte en vigor', 'passport'),
      doc('Plan de negocio detallado', 'planNegocio'),
      doc('Formulario EX-07 cumplimentado', 'ex07'),
      doc('Acreditación de titulación o experiencia profesional', 'titulacion'),
    ],
    gestion: [
      doc('Pasaporte en vigor', 'passport'),
      doc('Plan de negocio detallado', 'planNegocio'),
      doc('Formulario EX-07 cumplimentado', 'ex07'),
      doc('Acreditación de titulación o experiencia profesional', 'titulacion'),
      doc('Justificación de medios económicos', 'mediosEconomicos'),
      doc('Licencias o permisos sectoriales necesarios', 'licencias'),
      doc('Justificante tasa modelo 790-052', 'tasa790_052'),
    ],
  },
  nacionalidad: {
    orientacion: [
      doc('Pasaporte en vigor', 'passport'),
      doc('NIE o TIE en vigor', 'nieTie'),
    ],
    revision: [
      doc('Pasaporte en vigor', 'passport'),
      doc('NIE o TIE en vigor', 'nieTie'),
      doc('Certificado de empadronamiento histórico', 'empadronamientoHistorico'),
      doc('Certificado de antecedentes penales del país de origen (apostillado)', 'antecedentespenales'),
      doc('Certificado de nacimiento apostillado', 'nacimiento'),
    ],
    gestion: [
      doc('Pasaporte en vigor', 'passport'),
      doc('NIE o TIE en vigor', 'nieTie'),
      doc('Certificado de empadronamiento histórico', 'empadronamientoHistorico'),
      doc('Certificado de antecedentes penales del país de origen (apostillado)', 'antecedentespenales'),
      doc('Certificado de nacimiento apostillado', 'nacimiento'),
      doc('Diploma DELE A2 o superior', 'dele'),
      doc('Diploma CCSE', 'ccse'),
      doc('Solicitud de nacionalidad (Ministerio de Justicia)', 'solicitudNacionalidad'),
    ],
  },
  nie: {
    orientacion: [
      doc('Pasaporte en vigor', 'passport'),
      doc('Justificación del motivo de la solicitud', 'motivoNIE'),
    ],
    revision: [
      doc('Pasaporte en vigor', 'passport'),
      doc('Justificación del motivo de la solicitud', 'motivoNIE'),
      doc('Formulario EX-15 cumplimentado', 'ex15'),
      doc('Justificante tasa modelo 790-012', 'tasa790_012'),
    ],
    gestion: [
      doc('Pasaporte en vigor', 'passport'),
      doc('Justificación del motivo de la solicitud', 'motivoNIE'),
      doc('Formulario EX-15 cumplimentado', 'ex15'),
      doc('Justificante tasa modelo 790-012', 'tasa790_012'),
      doc('Fotografía reciente (fondo blanco)', 'fotografia'),
    ],
  },
  ue: {
    orientacion: [
      doc('DNI o pasaporte comunitario en vigor', 'dniComunitario'),
    ],
    revision: [
      doc('DNI o pasaporte comunitario en vigor', 'dniComunitario'),
      doc('Formulario EX-18', 'ex18'),
      doc('Justificación de actividad (contrato de trabajo, matrícula o medios económicos)', 'actividad'),
    ],
    gestion: [
      doc('DNI o pasaporte comunitario en vigor', 'dniComunitario'),
      doc('Formulario EX-18', 'ex18'),
      doc('Justificación de actividad (contrato de trabajo, matrícula o medios económicos)', 'actividad'),
      doc('Póliza de seguro médico (si no cotiza en España)', 'seguroMedicoUE'),
      doc('Justificante tasa modelo 790-012', 'tasa790_012'),
    ],
  },
};

export const TRAMITE_KEYS = {
  'Autorización de residencia inicial': 'residencia',
  'Renovación de TIE': 'tie',
  'Reagrupación familiar': 'reagrupacion',
  'Autorización de trabajo por cuenta ajena': 'trabajo_ajena',
  'Autorización de trabajo por cuenta propia': 'trabajo_propia',
  'Nacionalidad española por residencia': 'nacionalidad',
  'NIE': 'nie',
  'Certificado de registro UE': 'ue',
};

export const PLAN_KEYS = {
  '1': 'orientacion',
  '2': 'revision',
  '3': 'gestion',
  '4': 'gestion',
};
